"""Init

Revision ID: 83f75cd41640
Revises: 
Create Date: 2023-02-11 20:13:54.234807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f75cd41640'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sec_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cik', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=150), nullable=True),
    sa.Column('irsNumber', sa.Integer(), nullable=True),
    sa.Column('stateOfIncorporation', sa.String(length=25), nullable=True),
    sa.Column('street1', sa.String(length=250), nullable=True),
    sa.Column('street2', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=250), nullable=True),
    sa.Column('zip', sa.String(length=25), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik')
    )
    op.create_table('sec_company_ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_cik', sa.Integer(), nullable=False),
    sa.Column('owner_cik', sa.Integer(), nullable=False),
    sa.Column('securitiesOwned', sa.Integer(), nullable=True),
    sa.Column('isDirector', sa.Boolean(), nullable=True),
    sa.Column('isOfficer', sa.Boolean(), nullable=True),
    sa.Column('isTenPercentOwner', sa.Boolean(), nullable=True),
    sa.Column('isOther', sa.Boolean(), nullable=True),
    sa.Column('officerTitle', sa.String(length=150), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_cik'),
    sa.UniqueConstraint('owner_cik')
    )
    op.create_table('sec_derivative',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_cik', sa.Integer(), nullable=False),
    sa.Column('owner_cik', sa.Integer(), nullable=False),
    sa.Column('securityTitle', sa.String(length=150), nullable=True),
    sa.Column('conversionOrExercisePrice', sa.String(length=150), nullable=True),
    sa.Column('exerciseDate', sa.String(length=25), nullable=True),
    sa.Column('expirationDate', sa.String(length=25), nullable=True),
    sa.Column('underlyingSecurityTitle', sa.String(length=150), nullable=True),
    sa.Column('underlyingSecurityShares', sa.String(length=150), nullable=True),
    sa.Column('directOrIndirect', sa.String(length=25), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_cik'),
    sa.UniqueConstraint('owner_cik')
    )
    op.create_table('sec_filing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accessionNumber', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.Column('fullSubmissionUrl', sa.String(length=250), nullable=True),
    sa.Column('filingDetailsUrl', sa.String(length=250), nullable=True),
    sa.Column('filingDetailsFilename', sa.String(length=250), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('periodOfReport', sa.String(length=15), nullable=True),
    sa.Column('filedDate', sa.String(length=15), nullable=True),
    sa.Column('changeDate', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sec_non_derivative',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_cik', sa.Integer(), nullable=False),
    sa.Column('owner_cik', sa.Integer(), nullable=False),
    sa.Column('securityTitle', sa.String(length=150), nullable=True),
    sa.Column('securityValue', sa.String(length=150), nullable=True),
    sa.Column('directOrIndirect', sa.String(length=25), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_cik'),
    sa.UniqueConstraint('owner_cik')
    )
    op.create_table('sec_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cik', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('street1', sa.String(length=250), nullable=True),
    sa.Column('street2', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=250), nullable=True),
    sa.Column('zip', sa.String(length=25), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sec_person')
    op.drop_table('sec_non_derivative')
    op.drop_table('sec_filing')
    op.drop_table('sec_derivative')
    op.drop_table('sec_company_ownership')
    op.drop_table('sec_company')
    # ### end Alembic commands ###
